# Generated by Django 3.2.9 on 2021-12-20 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapID', models.CharField(max_length=32)),
                ('x', models.DecimalField(decimal_places=2, max_digits=10)),
                ('y', models.DecimalField(decimal_places=2, max_digits=10)),
                ('load_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_RSSI', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_Q', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_R', models.DecimalField(decimal_places=2, max_digits=10)),
                ('require_date', models.DateField()),
                ('mapID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='API.map')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_loc_x', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_loc_y', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_kal_p1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_kal_p2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_kal_p3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_kal_p4', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_kal_Q', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_kal_R', models.DecimalField(decimal_places=2, max_digits=10)),
                ('require_date', models.DateField()),
                ('customermap', models.ManyToManyField(to='API.CustomerMap')),
                ('mapID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='API.map')),
            ],
        ),
    ]
