# Generated by Django 3.2.9 on 2021-12-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='beaconID',
            field=models.CharField(default='', max_length=50),
        ),
    ]
