# Generated by Django 3.2.9 on 2021-12-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_map_beaconid'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapOpe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
